# Generated by Django 3.2.12 on 2022-02-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_date'),
        ('article_tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_tag',
            new_name='Articletag',
        ),
    ]
