# Generated by Django 3.2.12 on 2022-02-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_date'),
        ('article_tag', '0002_rename_article_tag_articletag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articletag',
            new_name='Article_tag',
        ),
    ]
