# Generated by Django 3.2.12 on 2022-02-22 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 10, 11, 1, 908272)),
        ),
        migrations.AlterField(
            model_name='article',
            name='draft',
            field=models.BooleanField(),
        ),
    ]
