# Generated by Django 3.2.12 on 2022-02-22 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20220222_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 10, 13, 38, 863212)),
        ),
        migrations.AlterField(
            model_name='article',
            name='draft',
            field=models.CharField(default='False', max_length=7),
        ),
    ]
