# Generated by Django 3.2.12 on 2022-02-22 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20220222_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 11, 32, 38, 555356)),
        ),
    ]
